{{- if .Values.generateCredential }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.server.admin.secretName }}
type: Opaque
stringData:
  ADMIN_USER: {{ .Values.server.admin.user }}
  ADMIN_PASSWORD: {{ .Values.server.admin.password }}
{{- end }}
